export const CRM = "CRM"

export const INCREEMENT = "INCREEMENT"

export const DECREEMENT = "DECREEMENT"

export const SELECTED_PEOPLES = "SELECTED_PEOPLES"

export const SELECTED_COMPANIES = "SELECTED_COMPANIES"
